# Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-reference.html
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Pressbrief:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pressbrief
      Handler: runner.lambda_handler
      Role: !GetAtt PressbriefRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            pass
      Runtime: python3.6
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          DROPBOX_ACCESS_TOKEN: !Ref DropboxAccessToken
          LIMIT_PER_RSS: !Ref LimitPerRSS
          URL2QR: !Ref URL2QR
  PressbriefRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PressbriefRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: arn:aws:logs:*:*:*
  PressbriefSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: PressbriefSchedule
      ScheduleExpression: !Sub cron(0 0 * * ? *)
      Targets:
        - Id: PressbriefScheduleTarget
          Arn:
            Fn::GetAtt:
              - Pressbrief
              - Arn
      State: ENABLED
  PressbriefInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Pressbrief
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - PressbriefSchedule
          - Arn
Parameters:
  DropboxAccessToken:
    Type: String
    Description: An access token to save briefs on Dropbox.
  LimitPerRSS:
    Type: Number
    Description: The maximum number of news from one RSS feed to include.
    Default: 4
    MinValue: 1
  URL2QR:
    Type: String
    Description: The flag indicating whether URLs should be converted to QR codes.
    Default: "True"
    AllowedValues:
      - "True"
      - "False"