version: '3'

services:
  pressbrief:
    container_name: pressbrief
    build: .
    image: pressbrief
    env_file: 
      - .env
    environment:
      # - DROPBOX_ACCESS_TOKEN=
      - LIMIT_PER_RSS=8
      - URL2QR=True
      - BRIEF_OUTPUT=/output
    volumes:
      # dir for resulting briefs
      - ${HOST_OUTPUT}:${BRIEF_OUTPUT}